/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pharmacy.view;
import com.pharmacy.database.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class InventoryForm extends javax.swing.JFrame {
    private void loadInventoryData() {
    DefaultTableModel model = (DefaultTableModel) tableProducts.getModel();
    model.setRowCount(0); // Clear existing table rows

    String query = "SELECT p.product_id, p.product_name, c.category_name, p.unit_price, p.stock_quantity, p.expiry_date " +
                   "FROM products p LEFT JOIN categories c ON p.category_id = c.category_id";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(query);
         ResultSet rs = pstmt.executeQuery()) {

        while (rs.next()) {
            Object[] row = {
                rs.getInt("product_id"),
                rs.getString("product_name"),
                rs.getString("category_name"),
                rs.getDouble("unit_price"),
                rs.getInt("stock_quantity"),
                rs.getDate("expiry_date")
            };
            model.addRow(row);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading inventory: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InventoryForm.class.getName());

    /**
     * Creates new form InventoryForm
     */
    public InventoryForm() {
        
        initComponents();
        loadInventoryData();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProducts = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 18, 96));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pharmacy Inventory Management System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 510, -1));

        jPanel2.setBackground(new java.awt.Color(56, 105, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel2.setText("Search Product:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        txtSearch.addActionListener(this::txtSearchActionPerformed);
        jPanel2.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 220, -1));

        btnSearch.setBackground(new java.awt.Color(51, 153, 255));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        jPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        tableProducts.setBackground(new java.awt.Color(204, 204, 204));
        tableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Product Name", "Category", "Unit Price", "Stock Quantity", "Expiry Date"
            }
        ));
        jScrollPane1.setViewportView(tableProducts);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 580, 200));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 740, 320));

        jPanel3.setBackground(new java.awt.Color(15, 15, 78));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        jPanel3.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        jPanel3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);
        jPanel3.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        jPanel3.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jButtonBack.setText("Back to dashboard");
        jButtonBack.addActionListener(this::jButtonBackActionPerformed);
        jPanel3.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 180, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 740, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 750, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
String keyword = txtSearch.getText().trim();
    DefaultTableModel model = (DefaultTableModel) tableProducts.getModel();
    model.setRowCount(0);

    String query = "SELECT p.product_id, p.product_name, c.category_name, p.unit_price, p.stock_quantity, p.expiry_date " +
                   "FROM products p LEFT JOIN categories c ON p.category_id = c.category_id " +
                   "WHERE p.product_name LIKE ?";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(query)) {
        
        pstmt.setString(1, "%" + keyword + "%");
        
        try (ResultSet rs = pstmt.executeQuery()) {
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("product_id"),
                    rs.getString("product_name"),
                    rs.getString("category_name"),
                    rs.getDouble("unit_price"),
                    rs.getInt("stock_quantity"),
                    rs.getDate("expiry_date")
                });
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Search error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
   // 1. Prompt user for all required database fields matching your schema
        String productCode = JOptionPane.showInputDialog(this, "Enter Product Code (e.g., MED009):");
        if (productCode == null || productCode.trim().isEmpty()) return;

        String productName = JOptionPane.showInputDialog(this, "Enter Product Name:");
        if (productName == null || productName.trim().isEmpty()) return;

        String categoryStr = JOptionPane.showInputDialog(this, "Enter Category ID (e.g., 1, 2, 3):");
        if (categoryStr == null || categoryStr.trim().isEmpty()) return;

        String supplierStr = JOptionPane.showInputDialog(this, "Enter Supplier ID (e.g., 1, 2, 3):");
        if (supplierStr == null || supplierStr.trim().isEmpty()) return;

        String priceStr = JOptionPane.showInputDialog(this, "Enter Unit Price (Selling Price):");
        if (priceStr == null || priceStr.trim().isEmpty()) return;

        String costPriceStr = JOptionPane.showInputDialog(this, "Enter Cost Price:");
        if (costPriceStr == null || costPriceStr.trim().isEmpty()) return;

        String qtyStr = JOptionPane.showInputDialog(this, "Enter Stock Quantity:");
        if (qtyStr == null || qtyStr.trim().isEmpty()) return;

        String reorderStr = JOptionPane.showInputDialog(this, "Enter Reorder Level (e.g., 20):");
        if (reorderStr == null || reorderStr.trim().isEmpty()) return;

        String expiryStr = JOptionPane.showInputDialog(this, "Enter Expiry Date (YYYY-MM-DD):");
        if (expiryStr == null || expiryStr.trim().isEmpty()) return;

        // 2. Full SQL INSERT statement matching all columns
        String query = "INSERT INTO products (product_code, product_name, category_id, supplier_id, unit_price, cost_price, stock_quantity, reorder_level, expiry_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query)) {
            
            pstmt.setString(1, productCode.trim());
            pstmt.setString(2, productName.trim());
            pstmt.setInt(3, Integer.parseInt(categoryStr.trim()));
            pstmt.setInt(4, Integer.parseInt(supplierStr.trim()));
            pstmt.setDouble(5, Double.parseDouble(priceStr.trim()));
            pstmt.setDouble(6, Double.parseDouble(costPriceStr.trim()));
            pstmt.setInt(7, Integer.parseInt(qtyStr.trim()));
            pstmt.setInt(8, Integer.parseInt(reorderStr.trim()));
            pstmt.setString(9, expiryStr.trim());
            
            int rowsInserted = pstmt.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Product added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadInventoryData(); // Refresh table automatically
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values for IDs, prices, quantities, or reorder levels.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
// 1. Check if a row is selected in the table
    int selectedRow = tableProducts.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a product from the table to update.", "Selection Required", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Grab the product_id and existing values from the selected row
    int productId = (int) tableProducts.getValueAt(selectedRow, 0);
    String currentName = tableProducts.getValueAt(selectedRow, 1).toString();
    Object currentPrice = tableProducts.getValueAt(selectedRow, 3);
    Object currentStock = tableProducts.getValueAt(selectedRow, 4);

    // 3. Prompt user for updated details (pre-filled with current values)
    String newName = JOptionPane.showInputDialog(this, "Update Product Name:", currentName);
    if (newName == null) return; // User clicked Cancel

    String newPriceStr = JOptionPane.showInputDialog(this, "Update Unit Price:", currentPrice);
    if (newPriceStr == null) return;

    String newStockStr = JOptionPane.showInputDialog(this, "Update Stock Quantity:", currentStock);
    if (newStockStr == null) return;

    // 4. Execute the SQL UPDATE statement
    String query = "UPDATE products SET product_name = ?, unit_price = ?, stock_quantity = ? WHERE product_id = ?";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(query)) {
        
        pstmt.setString(1, newName.trim());
        pstmt.setDouble(2, Double.parseDouble(newPriceStr.trim()));
        pstmt.setInt(3, Integer.parseInt(newStockStr.trim()));
        pstmt.setInt(4, productId);
        
        int rowsUpdated = pstmt.executeUpdate();
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(this, "Product updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadInventoryData(); // Refresh table automatically
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter valid numeric values for price and stock quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
// 1. Check if a row is selected in the table
    int selectedRow = tableProducts.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a product from the table to delete.", "Selection Required", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Grab the product_id and product name from the selected row
    int productId = (int) tableProducts.getValueAt(selectedRow, 0);
    String productName = tableProducts.getValueAt(selectedRow, 1).toString();

    // 3. Ask for user confirmation before deleting
    int confirm = JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to delete '" + productName + "'?", 
        "Confirm Deletion", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.WARNING_MESSAGE
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return; // User cancelled
    }

    // 4. Execute the SQL DELETE statement
    String query = "DELETE FROM products WHERE product_id = ?";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(query)) {
        
        pstmt.setInt(1, productId);
        
        int rowsDeleted = pstmt.executeUpdate();
        if (rowsDeleted > 0) {
            JOptionPane.showMessageDialog(this, "Product deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadInventoryData(); // Refresh table automatically
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
                                        
    // Clear any active search filter text if you have one
    txtSearch.setText(""); 
    
    // Reload all product rows from the database
    loadInventoryData();
    
    JOptionPane.showMessageDialog(this, "Inventory list refreshed!", "Refreshed", JOptionPane.INFORMATION_MESSAGE);
       // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
// 1. Create an instance of your admin dashboard window
    AdminDashboard dashboard = new AdminDashboard();
    
    // 2. Make the dashboard visible
    dashboard.setVisible(true);
    
    // 3. Close the current module window
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InventoryForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProducts;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
