/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pharmacy.view;

import com.pharmacy.database.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ReportsForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportsForm.class.getName());

    /**
     * Creates new form ReportsForm
     */
    public ReportsForm() {
        initComponents();
        setLocationRelativeTo(null); // Center on screen
        loadLowStockReport(); // Default load low stock report on open
    }

    private void loadLowStockReport() {
        DefaultTableModel model = (DefaultTableModel) tableReports.getModel();
        model.setRowCount(0); // Clear existing rows
        
        // Update column headers for Stock Report
        model.setColumnIdentifiers(new String[]{"ID", "Product Name", "Stock Quantity", "Unit Price", "Expiry Date"});

        String query = "SELECT product_id, product_name, stock_quantity, unit_price, expiry_date " +
                       "FROM products WHERE stock_quantity <= 10 ORDER BY stock_quantity ASC";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query);
             ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("product_id"),
                    rs.getString("product_name"),
                    rs.getInt("stock_quantity"),
                    rs.getDouble("unit_price"),
                    rs.getDate("expiry_date")
                };
                model.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading low stock report: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // 2. Sales History Report Query
    private void loadSalesHistoryReport() {
        DefaultTableModel model = (DefaultTableModel) tableReports.getModel();
        model.setRowCount(0);
        
        // Update column headers for Sales Report
        model.setColumnIdentifiers(new String[]{"Sale ID", "Total Amount (LKR)", "Sale Date & Time"});

        String query = "SELECT sale_id, total_amount, sale_date FROM sales ORDER BY sale_date DESC";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query);
             ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("sale_id"),
                    rs.getDouble("total_amount"),
                    rs.getTimestamp("sale_date")
                };
                model.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Note: If sales table isn't created yet, complete the POS billing terminal first. Error: " + e.getMessage(), "Sales Report Notice", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReports = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnLowStock = new javax.swing.JButton();
        btnSales = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("System Reports Dashboard");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(24, 24, 115));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inventory & Sales Reports");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        tableReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableReports);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 640, 250));

        jPanel2.setBackground(new java.awt.Color(56, 105, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLowStock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLowStock.setText("Low Stock Alert");
        btnLowStock.addActionListener(this::btnLowStockActionPerformed);
        jPanel2.add(btnLowStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 35));

        btnSales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSales.setText("Sales History Report");
        btnSales.addActionListener(this::btnSalesActionPerformed);
        jPanel2.add(btnSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 180, 35));

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);
        jPanel2.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 140, 35));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 640, 75));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>                        

    private void btnLowStockActionPerformed(java.awt.event.ActionEvent evt) {                                          
        loadLowStockReport();
    }                                         

    private void btnSalesActionPerformed(java.awt.event.ActionEvent evt) {                                         
        loadSalesHistoryReport();
    }                                        

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {                                           
        loadLowStockReport();
        JOptionPane.showMessageDialog(this, "Reports data reloaded!", "Refreshed", JOptionPane.INFORMATION_MESSAGE);
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportsForm().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnLowStock;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableReports;
    // End of variables declaration                   
}