/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to license this template
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pharmacy.view;

import com.pharmacy.database.DBConnection;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Admin
 */
public class ReportsForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportsForm.class.getName());

    /**
     * Creates new form ReportsForm
     */
    public ReportsForm() {
        initComponents();
        setLocationRelativeTo(null); // Center on screen
        loadSalesAuditTable(); // Default load sales audit data into table on open
    }

    // 1. Table Data Loader: Sales & Invoice Audit Summary
    private void loadSalesAuditTable() {
        DefaultTableModel model = (DefaultTableModel) tableReports.getModel();
        model.setRowCount(0); // Clear existing rows
        
        model.setColumnIdentifiers(new String[]{"Invoice ID", "Date & Time", "Customer", "Cashier", "Payment Method", "Total (LKR)"});
        jLabel1.setText("Sales & Invoice Audit Report");

        String query = "SELECT i.invoice_id, i.transaction_date, i.total_amount, i.payment_method, " +
                       "c.customer_name, u.full_name AS cashier_name " +
                       "FROM invoices i " +
                       "LEFT JOIN customers c ON i.customer_id = c.customer_id " +
                       "LEFT JOIN users u ON i.user_id = u.user_id " +
                       "ORDER BY i.invoice_id DESC";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query);
             ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("invoice_id"),
                    rs.getTimestamp("transaction_date"),
                    rs.getString("customer_name"),
                    rs.getString("cashier_name"),
                    rs.getString("payment_method"),
                    rs.getDouble("total_amount")
                };
                model.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading sales audit table: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // 2. JasperReports Generator: Sales & Invoice Audit Report Viewer
    private void generateSalesAuditJasperReport() {
        try (Connection conn = DBConnection.getConnection();
             InputStream reportStream = new java.io.FileInputStream("src/reports/Sales.jasper")) {
            
            JasperPrint print = JasperFillManager.fillReport(reportStream, new HashMap<>(), conn);
            JasperViewer.viewReport(print, false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error generating Sales Audit Report: " + e.getMessage(), "JasperReports Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    // 3. JasperReports Generator: Low Stock Report Viewer
    private void generateLowStockJasperReport() {
        try (Connection conn = DBConnection.getConnection();
             InputStream reportStream = new java.io.FileInputStream("src/reports/LowStockReport.jasper")) {
            
            JasperPrint print = JasperFillManager.fillReport(reportStream, new HashMap<>(), conn);
            JasperViewer.viewReport(print, false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error generating Low Stock Report: " + e.getMessage(), "JasperReports Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReports = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnViewAuditReport = new javax.swing.JButton();
        btnViewLowStockReport = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pharmacy System Reports Dashboard");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(24, 24, 115));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sales & Invoice Audit Report");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        tableReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableReports);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 750, 270));

        jPanel2.setBackground(new java.awt.Color(56, 105, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewAuditReport.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnViewAuditReport.setText("View Sales Report");
        btnViewAuditReport.addActionListener(this::btnViewAuditReportActionPerformed);
        jPanel2.add(btnViewAuditReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 160, 35));

        btnViewLowStockReport.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnViewLowStockReport.setText("View Low Stock Report");
        btnViewLowStockReport.addActionListener(this::btnViewLowStockReportActionPerformed);
        jPanel2.add(btnViewLowStockReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 15, 180, 35));

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnRefresh.setText("Refresh Table");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);
        jPanel2.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 15, 150, 35));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 15, 110, 35));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 750, 65));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 455));

        pack();
    }// </editor-fold>                        

    private void btnViewAuditReportActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        generateSalesAuditJasperReport();
    }                                                  

    private void btnViewLowStockReportActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        generateLowStockJasperReport();
    }                                                     

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {                                           
        loadSalesAuditTable();
        JOptionPane.showMessageDialog(this, "Sales Audit table reloaded!", "Refreshed", JOptionPane.INFORMATION_MESSAGE);
    }                                          

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {                                        
        AdminDashboard dashboard = new AdminDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportsForm().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewAuditReport;
    private javax.swing.JButton btnViewLowStockReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableReports;
    // End of variables declaration                   
}